### ISSUE TITLE
On installation it throws custom.css not found

### ISSUE THREAD

**Issue by shivkumar-k** [frappe/frappe_theme#7]
I have installed frappe-theme on installation of frappe. 
Then on bench start it is throwing the following error.

**jinja2.exceptions.TemplateNotFound
TemplateNotFound: templates/includes/custom.css**

Anyway I have commented line 11 of "frappe-bench/apps/frappe_theme/frappe_theme/templates/base.html"

    {# <style>{% include "templates/includes/custom.css" %}</style> #}

**My Question is** : Why you have included that css line..Does it have any custom css or it is for user to add his own css in it?

**Comment by rmehta** [comment]
You should include a `custom.css` in any app where this is installed.
